config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # match 'users/sign_out' => "devise/sessions#destroy"

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'pages#home'

  get 'dashboard', to: 'pages#dashboard'

  resources :groups, only: [:new, :index, :create]

  resources :participations, only: [:new]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/balance.rb
class Balance < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/cook.rb
class Cook < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/creation.rb
class Creation < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/group.rb
class Group < ApplicationRecord

  has_one :creation
  has_one :user, through: :creation

  has_many :participations
  has_many :users, through: :participations

  has_many :balances
  has_many :messages
  has_many :occurences
  has_many :slot_times, through: :occurences

end

app/models/occurence.rb
class Occurence < ApplicationRecord
  belongs_to :slot_time
  belongs_to :group
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/presence.rb
class Presence < ApplicationRecord
  belongs_to :user
  belongs_to :occurence
end

app/models/slot_time.rb
class SlotTime < ApplicationRecord

  has_many :occurences
  has_many :groups, through: :occurences

end

app/models/turn.rb
class Turn < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord

  has_many :balances
  has_many :messages
  has_many :participations
  has_many :creations
  # has_many :groups, through: :creations
  has_many :groups, through: :participations


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  after_create :send_welcome_email


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :lastname)
    user_params['picture_url'] = auth.info.image_size
    user_params['token'] = auth.credentials.token
    user_params['token_expiry'] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email)

    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0, 20]
      user.save
    end

    return user
  end

  def self.from_google_omniauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h
    # data = auth.info ...
    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email:auth.info.email)
    unless user
        user = User.new(user_params)
        user.password = Devise.friendly_token[0,20]
        user.save
    end
    user
  end

  private

  def send_welcome_email
    # UserMailer.welcome(self).deliver_now
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.user = current_user
    if @group.save
      new_balance = Balance.new
      new_balance.group = @group
      new_balance.user = current_user
      new_balance.amount = 0
      new_balance.save
      redirect_to groups_path(@group)
    else
      render :new
    end
  end

  def index
    @groups = current_user.groups
  end


  private

  def group_params
    params.require(:group).permit(:title, :only_cookers)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: :home

  def home

  end

  def dashboard

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
      User
  end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participations_helper.rb
module ParticipationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LunchClubCode</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.min.css">
    <link href="https://fonts.googleapis.com/css?family=BioRhyme:200" rel="stylesheet">
    <%= action_cable_meta_tag %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->

    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
    <%= yield(:after_js) %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="background" style="background-image:  url(' <%= cl_image_path("sharing_food_wood_table_dpkhj9.jpg") %> ');" >

  <div class="personal_informations">
    <div class="profil_image"> <%= image_tag current_user.picture_url %> </div>
  </div>

  <div class="reminder_banner">
  </div>

  <div class="linked_groups">
  </div>

  <%= render 'shared/linker_icons' %>
  <%= render 'shared/home_linker' %>

</div>

app/views/pages/home.html.erb
<div class="background_home grid" >

<% if user_signed_in? %>
  <div class="group_corner">
    <%= link_to(groups_path) do %>
      <div class="group_link"></div>
    <% end %>
  </div>
  <div class="creation_corner"></div>
  <div class="dashboard_corner"></div>
  <div class="participation_corner"></div>

  <div class="top"></div>
  <div class="left"></div>
  <div class="bottom">
    <%= link_to destroy_user_session_path, method: :delete do %>
      <div class="kill_session"><i class="fa fa-sign-out"></i><%= t(".sign_out", default: " Log out") %></div>
    <% end %>
  </div>
  <div class="right"></div>
<% end %>

  <div class="main">

    <div id="application_title">
      <h1>Lunch Club</h1>
      <p>C'est Adrien qui fait la popotte demain.</p>
    </div>

    <% if user_signed_in? %>

      <div class="home_icons">
        <%= link_to(groups_path) do  %>
          <div class="groups_icon icon">
            <%= image_tag("groups.svg") %>
          </div>
        <% end %>
        <%= link_to(new_group_path) do %>
          <div class="creation_icon icon">
            <%= image_tag("create_group_noun.svg") %>
          </div>
        <% end %>
        <%= link_to(dashboard_path) do %>
          <div class="dashboard_icon icon">
            <%= image_tag("home.svg") %>
          </div>
        <% end %>
        <%= link_to(new_participation_path) do %>
          <div class="participation_icon icon">
            <%= image_tag("group_men_noun.svg") %>
          </div>
        <% end %>
      </div>

    <% else %>

      <%#= render "welcome/sign_up_modal" %>

      <div id="log_in_modal" class="modal fade">
        <div class="modal-dialog">
          <div class="modals-content">

            <div class="modals-header modals-field">
              <p class="modals-title">Log In</p>
            </div>

            <div class="modals-body modals-field">
              <div class="modals-moose_area">
                <%= image_tag("modals_moose_head.svg", class: "modals-mascotte") %>
              </div>

              <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <%= devise_error_messages! %>
                <%= f.input :email, placeholder: 'user@domain.com', autofocus: true, label: false %>
                <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %><br />
                <%= f.input :password, placeholder: '••••••••', autocomplete: "off", label: false %>
                <% if devise_mapping.rememberable? -%>
                  <%= f.input_field :remember_me, inline_label: 'Oui, se souvenir de moi', as: :boolean %>
                <% end -%><br />
                <div class="modals-submit_area"><%= f.submit "Log in", class: "btn modals-submit_button", label: 'log in' %></div>
              <% end %>

              <div class="modals-first_footer modals-field">
                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button> -->
                <%#= render "devise/shared/links" %>
                <%- resource_class.omniauth_providers.each do |provider| %>
                  <% if provider == :google_oauth2 %>
                    <%= link_to(omniauth_authorize_path(resource_name, provider)) do %>
                      <i class="fa fa-google-plus" data-toggle="tooltip" data-placement="left" title="Sign in through Google" aria-hidden="true"></i>
                    <% end %>
                  <% elsif provider == :facebook %>
                    <%= link_to(omniauth_authorize_path(resource_name, provider)) do %>
                      <i class="fa fa-facebook-square" data-toggle="tooltip" data-placement="right" title="Sign in through Facebook" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                <% end -%>
              </div>
            </div>

            <div class="modals-second_footer">
              <%= link_to("Sign up", "#sign_up_modal", "data-toggle" => "modal") %>
            </div>

          </div>
        </div>
      </div>


      <div id="sign_up_modal" class="modal fade">
        <div class="modal-dialog">
          <div class="modals-content">

            <div class="modals-header modals-field">
              <p class="modals-title">Sign Up</p>
            </div>

            <div class="modals-body modals-field">
              <div class="modals-moose_area">
                <%= image_tag("modals_moose_head.svg", class: "modals-mascotte") %>
              </div>

              <%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
                <%= devise_error_messages! %>
                <%= f.input :email, placeholder: 'user@domain.com', autofocus: true, label: false %>
                <% if @minimum_password_length %>
                  <em>(<%= @minimum_password_length %> characters minimum)</em>
                <% end %><br />
                <%= f.input :password, placeholder: '••••••••', autocomplete: "off", label: false %>
                <% if devise_mapping.rememberable? -%>
                  <%= f.input_field :remember_me, inline_label: 'Oui, se souvenir de moi', as: :boolean %>
                <% end -%><br />
                <div class="modals-submit_area"><%= f.submit "Sign up", class: "btn modals-submit_button", label: 'Sign up' %></div>
              <% end %>

              <div class="modals-first_footer modals-field">
                <%- resource_class.omniauth_providers.each do |provider| %>
                  <% if provider == :google_oauth2 %>
                    <%= link_to(omniauth_authorize_path(resource_name, provider)) do %>
                      <i class="fa fa-google-plus" data-toggle="tooltip" data-placement="left" title="Sign up through Google" aria-hidden="true"></i>
                    <% end %>
                  <% elsif provider == :facebook %>
                    <%= link_to(omniauth_authorize_path(resource_name, provider)) do %>
                      <i class="fa fa-facebook-square" data-toggle="tooltip" data-placement="right" title="Sign up through Facebook" aria-hidden="true"></i>
                    <% end %>
                  <% end %>
                <% end -%>
              </div>
            </div>

            <div class="modals-second_footer">
              <%= link_to("Log in", "#log_in_modal", "data-toggle" => "modal") %>
            </div>

          </div>
        </div>
      </div>

<!-- <div class="modal fade" id="sign_up_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="Sign_up_modal">Sign up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>



        <div class="modal-body">


        </div>

        <div class="modal-footer">

        </div>

      </div>
      </div>
    </div>
  </div>
</div> -->


      <div class="moose_area">
        <div class="moose_head"><%= image_tag("moose_head.svg") %></div>
      </div>

      <div class="register_area">
        <a href="#log_in_modal" role="" class="" data-toggle="modal" data-backdrop="true">
        <%#= link_to("/users/sign_in", class: ".sign_in") do  %>
          <div class="register_button btn btn-success">Join Us</div>
        <%# end %>
        </a>
      </div>

      <a href="#">
        <div class="about_us">
          <div class="about_us_scroll_button"><p>About Us</p></div>
        </div>
      </a>

      <!-- <div class="sign_links">

        <div class="sign_up_link"> -->



          <!-- <a href="#" role="button" data-toggle="modal"></a> -->



          <!-- <div class="modal fade" id="my_modal">
            <div class="modal-content">
              <div class="modal-body">Let's see</div>
              <div class="modal-footer">
                <div class="btn btn-default" type="button" data-dismiss="modal">Close</div>
              </div>
            </div>
          </div> -->


          <!-- <div id="my_modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                  <h3 id="myModalLabel">Modal header</h3>
                </div>
                <div class="modal-body">
                  <p>One fine body…</p>
                </div>
                <div class="modal-footer">
                  <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                  <button class="btn btn-primary">Save changes</button>
                </div>
              </div>
            </div>
          </div> -->

          <!-- Modal HTML -->




                      <!-- Button trigger modal -->
          <!-- <a href="#sign_up_modal" role="button" class="btn btn-large btn-primary" data-toggle="modal">Nous Rejoindre</a> -->


        <!--   Button HTML (to Trigger Modal) -->
          <!-- <a href="#myModal" role="button" class="btn btn-large btn-primary" data-toggle="modal">Launch Demo Modal</a> -->



          <%#= link_to("/users/sign_up", class: ".sign_up") do %>
            <%#= image_tag("board_signup.svg") %>
          <%# end %>
        <!-- </div>

      </div> -->




    <% end %>

  </div>



</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <!-- <div class="alert alert-info alert-dismissible fade in" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button> -->


    <!-- <div class="alert alert-info alert-dismissable fade in">
      <%#= notice %>
      <a href="#" class="close" data-dismiss="alert">&times;</a>
    </div>
 -->

  <div class="alert alert-info alert-dismissible" data-auto-dismiss="2000" role="alert">
    <a href="#" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></a>
    <%= notice %>
  </div>


  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_home_linker.html.erb
<%= link_to root_path do %>
  <%= cl_image_tag("giraffe_xy7zwb.svg") %>
<% end %>

app/views/shared/_linker_icons.html.erb
<%= link_to 'Groups', groups_path %>
<%= link_to 'Create group', new_group_path %>
<%= link_to 'Dashboard', dashboard_path %>
<%= link_to 'Join group', new_participation_path %>

app/views/welcome/_sign_up_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="sign_up_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="Sign_up_modal">Sign up</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>

        <div class="modal-body">
          <%= devise_error_messages! %>
          <div class="field">
            <%= f.label :email %><br />
            <%= f.email_field :email, autofocus: true %>
          </div>
          <div class="field">
            <%= f.label :password %>
            <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>
        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
          <div class="actions">
            <%= f.submit "Sign up" %>
          </div>
        </div>

      <% end %>
        <%= render "devise/shared/links" %>

      </div>
      </div>
    </div>
  </div>
</div>